---

- name: "Deploying a test site"
  hosts: amazon
  become: yes
  vars_files:
    - variables.yml

  tasks:

    - name: "Installing apache webserver"
      yum:
        name: httpd
        state: present
    - name: "Webserver - copying conf from httpd.conf.js"
      template:
        src: httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"

    - name: "Restarting apache"
      service:
        name: httpd
        state: restarted

